# Generated by Django 2.2.3 on 2020-10-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField(default='还没有任何介绍')),
                ('subtitle', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Area')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesName',
            fields=[
                ('name', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Language')),
                ('mid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo')),
            ],
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Version'),
        ),
    ]
