# Generated by Django 2.2.3 on 2020-10-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201027_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviesName',
        ),
    ]
