# Generated by Django 2.2.3 on 2020-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_delete_moviesname'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='areaname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='version',
            name='versionname',
            field=models.CharField(max_length=50),
        ),
    ]
