# Generated by Django 2.2.3 on 2020-10-29 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_copyrightinfo_orderinfo_rightinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightinfo',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.CopyRightinfo', verbose_name='版权链'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='end_time',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='movies_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo', verbose_name='电影信息'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='版权名称'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='oder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Orderinfo', verbose_name='订单信息'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='remark',
            field=models.CharField(max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.RightInfo', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='star_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='warning',
            field=models.BooleanField(verbose_name='是否开启预警'),
        ),
        migrations.AlterField(
            model_name='copyrightinfo',
            name='warning_time',
            field=models.IntegerField(verbose_name='预警时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='paystyle',
            field=models.CharField(max_length=255, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='sellid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selluser', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyuser', to=settings.AUTH_USER_MODEL, verbose_name='买家'),
        ),
        migrations.AlterField(
            model_name='rightinfo',
            name='bankruptcy',
            field=models.TextField(verbose_name='破产条例描述'),
        ),
        migrations.AlterField(
            model_name='rightinfo',
            name='description',
            field=models.TextField(verbose_name='权利描述'),
        ),
        migrations.AlterField(
            model_name='rightinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='权限名'),
        ),
    ]
