# Generated by Django 2.2.3 on 2020-10-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201029_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightinfo',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.CopyRightinfo', verbose_name='版权链'),
        ),
    ]
